version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nbra
      MYSQL_PASSWORD: nbra
      MYSQL_DATABASE: estatsdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/estatsdump.sql:/docker-entrypoint-initdb.d/estatsdump.sql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql

  generator:
    image: nbrandtner/datagenerator:latest
    container_name: datagenerator
    restart: always
    depends_on:
      - mysql

volumes:
  mysql_data: