version: '3'

services:
  mysql:
    image: mysql
    container_name: proj2223_estatsaustria_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nbra
      MYSQL_PASSWORD: nbra
      MYSQL_DATABASE: estatsdb
      TZ: Europe/Vienna
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/estatsdump.sql:/docker-entrypoint-initdb.d/estatsdump.sql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: proj2223_estatsaustria_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      TZ: Europe/Vienna
    ports:
      - "8080:80"
    depends_on:
      - mysql

  generator:
    image: nbrandtner/datagenerator:latest
    container_name: proj2223_estatsaustria_datagenerator
    restart: always
    depends_on:
      - mysql
    environment:
      TZ: Europe/Vienna

volumes:
  mysql_data: